### ISSUE TITLE
[init] 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by hwangsunwoong** [TeamPmu/Pmu-Server#1]
## Issue 🍃
프로젝트 초기 세팅

## Todo 🌴
- [x] Issue 템플릿 추가
- [x] PR 템플릿 추가
- [x] Label 생성
- [x] .gitignore 설정
- [x] 프로젝트 아키텍처 설계
- [x] 팀 AWS 계정 생성
- [x] 팀 Docker Hub 계정 생성
- [x] EC2 세팅
- [x] RDS 세팅
- [x] S3 세팅
- [x] CI/CD 세팅
